apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- count: 2
  name: kratosvil-replica-app
images:
- name: 805778285334.dkr.ecr.us-east-1.amazonaws.com/kratosvil-replica-app
  newName: 805778285334.dkr.ecr.us-east-1.amazonaws.com/kratosvil-replica-app
  newTag: 4cd75ad308a4
